# .github/workflows/test.yml
name: Test

on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-14,clang++-17]
        std: [17,20,23]
    steps:
      - uses: actions/checkout@v3
      - name: Compile test
        run: ${{matrix.compiler}} -std=c++${{matrix.std}} -Wall -Wextra test.cpp -o test
      - name: Run test
        run: ./test
